APPLICATION_FLASH_ORIGIN = 0x00027000;
APPLICATION_FLASH_BYTES = 0x99000;
APPLICATION_RAM_ORIGIN = 0x2000E000;
APPLICATION_RAM_BYTES = 0x32000;
MIN_RUNTIME_STACK_BYTES = 68K;

MEMORY
{
  FLASH : ORIGIN = APPLICATION_FLASH_ORIGIN, LENGTH = APPLICATION_FLASH_BYTES
  RAM   : ORIGIN = APPLICATION_RAM_ORIGIN, LENGTH = APPLICATION_RAM_BYTES
}

ASSERT(
  ORIGIN(RAM) + LENGTH(RAM) - _stack_end >= MIN_RUNTIME_STACK_BYTES,
  "Static memory leaves too little runtime stack"
)
